language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install xenon

script:
  - xenon --max-absolute B --max-modules A --max-average A .
  - pytest

after_success:
  - pip install coveralls
  - coveralls
