# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='root_app.Category'),
        ),
    ]
