# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketedproduct',
            name='bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='root_app.BasketedProduct'),
        ),
    ]
